// This file is auto-generated by the Supabase CLI.
// Run: npx supabase gen types typescript --project-id <your-project-id> > src/types/database.ts

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          role: 'admin' | 'booster' | 'client' | 'support'
          username: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          role?: 'admin' | 'booster' | 'client' | 'support'
          username?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          role?: 'admin' | 'booster' | 'client' | 'support'
          username?: string | null
          avatar_url?: string | null
          updated_at?: string
        }
      }
      games: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string
          is_active: boolean
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url: string
          is_active?: boolean
        }
        Update: {
          name?: string
          slug?: string
          logo_url?: string
          is_active?: boolean
        }
      }
      games_services: {
        Row: {
          id: string
          game_id: string
          type: 'rank_boost' | 'win_boost' | 'duo_boost' | 'placement_matches' | 'unrated_matches'
          label: string
          base_price: number
          is_active: boolean
        }
        Insert: {
          id?: string
          game_id: string
          type: 'rank_boost' | 'win_boost' | 'duo_boost' | 'placement_matches' | 'unrated_matches'
          label: string
          base_price: number
          is_active?: boolean
        }
        Update: {
          game_id?: string
          type?: 'rank_boost' | 'win_boost' | 'duo_boost' | 'placement_matches' | 'unrated_matches'
          label?: string
          base_price?: number
          is_active?: boolean
        }
      }
      orders: {
        Row: {
          id: string
          client_id: string
          booster_id: string | null
          game_id: string
          service_id: string
          status: 'pending' | 'awaiting_payment' | 'in_progress' | 'completed' | 'cancelled' | 'dispute'
          price: number
          details: Record<string, unknown>
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          booster_id?: string | null
          game_id: string
          service_id: string
          status?: 'pending' | 'awaiting_payment' | 'in_progress' | 'completed' | 'cancelled' | 'dispute'
          price: number
          details?: Record<string, unknown>
          created_at?: string
          updated_at?: string
        }
        Update: {
          booster_id?: string | null
          status?: 'pending' | 'awaiting_payment' | 'in_progress' | 'completed' | 'cancelled' | 'dispute'
          price?: number
          details?: Record<string, unknown>
          updated_at?: string
        }
      }
      chat_messages: {
        Row: {
          id: string
          order_id: string
          sender_id: string
          content: string
          image_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          sender_id: string
          content: string
          image_url?: string | null
          created_at?: string
        }
        Update: {
          content?: string
          image_url?: string | null
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
